### ISSUE TITLE
FSDPv2 with Accelerate

### ISSUE THREAD

**Issue by johnsutor** [huggingface/optimum-tpu#51]
Are there any plans to integrate FSDPv2 as a plugin for Accelerate? I'd like to use SPMD with TPUs to train transformers.

**Comment by tengomucho** [comment]
Hi @johnsutor, FSDPv2 is already supported by accelerate, you need to enable SPMD before using it and you need to provide the configuration to use it, but other than that it should work.

**Comment by johnsutor** [comment]
Hi @tengomucho , that's fantastic, thank you!
